//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_Sponte_Live
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscricao
    {
        public int Id_Inscricao { get; set; }
        public Nullable<int> Id_Live { get; set; }
        public Nullable<int> Id_Inscrito { get; set; }
        public Nullable<decimal> vl_Inscricao { get; set; }
        public Nullable<System.DateTime> dt_Vencimento { get; set; }
        public Nullable<byte> status_Pag { get; set; }
    
        public virtual Inscrito Inscrito { get; set; }
        public virtual Live Live { get; set; }
    }
}
