//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_Sponte_Live
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscrito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscrito()
        {
            this.Inscricao = new HashSet<Inscricao>();
        }
    
        public int Id_Inscrito { get; set; }
        public string nm_Inscrito { get; set; }
        public Nullable<System.DateTime> dt_Nasci_Inscrito { get; set; }
        public string email_Inscrito { get; set; }
        public string insta_Inscrito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscricao> Inscricao { get; set; }
    }
}
