//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_Sponte_Live
{
    using System;
    using System.Collections.Generic;
    
    public partial class Live
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Live()
        {
            this.Inscricao = new HashSet<Inscricao>();
        }
    
        public int Id_Live { get; set; }
        public string nm_Live { get; set; }
        public int Id_Instrutor { get; set; }
        public Nullable<System.DateTime> dt_Live { get; set; }
        public Nullable<System.TimeSpan> hr_Live { get; set; }
        public Nullable<int> ds_tempo_Live { get; set; }
        public Nullable<decimal> vl_Live { get; set; }
    
        public virtual Instrutor Instrutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscricao> Inscricao { get; set; }
    }
}
